### ISSUE TITLE
Feature Request: support display of checkboxes

### ISSUE THREAD

**Issue by AmorFati-coder** [markmap/markmap#56]
Just like Typora
```
- [ ] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed
```

**Comment by gera2ld** [comment]
Can you make it more clear?

**Comment by AmorFati-coder** [comment]
Hh,Of course.

### Task List

Task lists are lists with items marked as either [ ] or [x] (incomplete or complete). For example:

``` markdown
- [ ] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed
```

You can change the complete/incomplete state by clicking on the checkbox before the item.

**Comment by gera2ld** [comment]
I guess the mentions and refs are not in this feature request, am I right?

**Comment by AmorFati-coder** [comment]
Yep! Sorry about my awful express.

**Comment by mwegrzyn-psnc** [comment]
in addition to displaying checkboxes it would be also great if one could check'em on markmap and hide all that are checked.

**Comment by gy-mate** [comment]
The original suggestion was implemented in #222.
